my_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ufeed/',include('ufeed.urls'))
]

ufeed/urls.py
from django import views
from django.urls import path
from . import views
from .views import Accept_view

app_name ='ufeed'

urlpatterns = [
    path('',views.home_page,name='home'),
    path('registration/',views.Register_view,name='register'),
    path('contact_info/',views.contact_info, name = 'contact'),
    path('sign_info/',views.login_user,name='sign_in'),
    path('donate/',views.donate_view, name='donate'),
    path('list_of_hotels', views.LOH, name='list'),
    path('accept/<int:pk>/',Accept_view.as_view(),name='delete'),
]

ufeed/models.py
from django.db import models
from django.core.validators import ProhibitNullCharactersValidator


# Create your models here.



class Register(models.Model):
    name = models.CharField(max_length=30 )
    email = models.EmailField()
    password = models.CharField(max_length=30 )
    contact = models.CharField(max_length=17)

    def __str__(self):
        return f"{self.name},{self.email},{self.password},{self.contact}"


class problem(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.name},{self.email},{self.subject},{self.message}"

class sign_in(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.email},{self.password}"

class donate(models.Model):
    name= models.CharField(max_length=50)
    contact = models.CharField(max_length=17)
    address = models.CharField(max_length=300)
    amount = models.IntegerField(unique=True, null=True)       

ufeed/views.py
from ast import Pass
from django.shortcuts import render,redirect
from django.urls import reverse, reverse_lazy
from . import models
from .models import donate
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.http import *
from django.views.generic import DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

def login_user(request):
    logout(request)
    username = password = ''
    if request.POST:
        username = request.POST['email']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                print("shazam")
                return redirect(reverse('ufeed:home'))
    return render(request, 'ufeed/sign_in.html')    


def Register_view(request):
    print(request.POST)
    if request.POST:
        name = request.POST['name']
        email = request.POST['email']
        password = request.POST['password']
        contact = request.POST['contact']
        user = User.objects.create_user(username=email,password=password,first_name=name)
        return redirect(reverse('ufeed:sign_in'))
    else:
        return render(request,'ufeed/Registration_form.html')

@login_required(login_url="ufeed:sign_in")
def contact_info(request):
    print(request.POST)
    if request.POST:
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        prob = models.problem.objects.create(name=name, email=email,subject=subject,message=message)
        send_mail(
            subject="Your Query has been Received",
            message=f"HI,{prob.name}"
            f"We have received your query and our team will respond to it as early as possible",
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[prob.email]
        )
        return redirect(reverse('ufeed:sign_in'))
    else:    
        return render(request,'ufeed/contact_info.html')

def home_page(request):
    return render(request, 'ufeed/home_page.html')

@login_required(login_url="ufeed:sign_in")
def donate_view(request):
        if request.POST:
            name = request.POST['name']
            contact = request.POST['contact']
            address = request.POST['address']
            amount = request.POST['amount']
            models.donate.objects.create(name=name, contact=contact,address=address, amount=amount)
            return redirect(reverse('ufeed:list'))
        else:
            return render(request, 'ufeed/donate.html')        

def LOH(request):
    un_data = donate.objects.all()
    data = un_data[::-1]
    return render(request, 'ufeed/LOH.html', {'data':data})     

class Accept_view(DeleteView):
    # Requires model_confirm_delete.html template name
    model = donate
    
    success_url = reverse_lazy('ufeed:home')
    

templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&family=Baloo+Bhai+2:wght@600&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Lusitana&display=swap" rel="stylesheet">
    <title>Document</title>
    <style>
        html,
        body {
            font-family: 'Lusitana', serif;
        }

        .navbar {
            background-color: #110202;
        }

        #navbarNavDropdown {
            margin-left: 530px;
        }

        li {
            margin-left: 15px;
        }

        .navbar-dark .navbar-nav .nav-link {
            color: #fff;
        }


        ul li:hover>ul,
        ul li ul:hover {
            visibility: visible;
            opacity: 1;
            display: block;
        }
    </style>


<body>


    <!-- new html file -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <img width="50px" height="50px" style="border-radius: 20px;" src="{% static 'ufeed/sidd1.png' %}"
                alt="please Reload webpage">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse mr-2" id="navbarNavDropdown">
                <ul class="navbar-nav mx-auto header">
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="{% url 'ufeed:home' %}">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ufeed:register' %}">REGISTER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ufeed:contact' %}">CONTACT US</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ufeed:sign_in' %}">SIGN IN</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            SERVICES
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'ufeed:donate' %}">Donate Food</a></li>
                            <li><a class="dropdown-item" href="{% url 'ufeed:list' %}">List of Hotels</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>





    {% block content %}

    {% endblock content %}

</body>

</html>

ufeed/templates/ufeed/LOH.html
{% extends 'base.html' %}

{% block content %}
<html>

<head>
    <style>
        button:hover {
            background-color: #fff;
            color: #04AA6D;
        }
    </style>
</head>

<body>
    <h1 style="text-align: center; margin-top: 10px;">List Of Hotels</h1>
    <form method="POST">
        {% csrf_token %}
        {% for student in data %}
        <div class="container-fluid" style="display: flex; justify-content: center; margin-top: 15px;">
            <div class="card" style="width: 25rem;">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><b>Name : </b>{{student.name}}</li>
                    <li class="list-group-item"><b>Contact :</b> {{student.contact}}</li>
                    <li class="list-group-item"><b>Address :</b> {{student.address}}</li>
                    <li class="list-group-item" id="id"><b>Amount :</b> {{student.amount}}</li>
                    <a
                            href="/ufeed/accept/{{student.id}}" style="text-decoration: none;color: #fff;text-align: center;background-color: #04AA6D;color: #fff;">Accept</a>
                </ul>
            </div>
        </div>
    </form>
    <br>
</body>

</html>


<script>

    $(document).ready(function () {
        $('button').click(function () {

        });
    });
</script>
{% endfor %}
{% endblock content %}

ufeed/templates/ufeed/Registration_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&family=Baloo+Bhai+2:wght@600&display=swap"
        rel="stylesheet">

</head>
<style>
        
body{
    background-color: rgb(241 235 235);;
}
*{
    margin: 0px;
    padding: 0px;
  }
  *{
      box-sizing: border-box;
  }
/* container */

.container{
    width: 44vw;
    /* height: 500px; */
    
    margin: 85px auto;
    background-color: white;
    padding: 20px;
}
input[type=text],input[type=password],input[type=email]{
    display: inline-block;
    padding: 10px;
    width: 100%;
    margin: 7px 0px 22px 0px;
   
    
}
hr{
    margin-bottom: 15px;
    border: 1px solid #f1f1f1;

}
.registerbtn{
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}
.registerbtn:hover{
    opacity: 0.8;
}
p{
  margin: 12px 0px;
}
.radio{
    padding: 2px;
    margin-bottom: 8px;
}
.radio label{
    font-weight: bold;
}

#logo{
    width: 10px;
    height: 75px;
}
#logo img{
    width: 63px;
    border-radius: 82px;
    height: 57px;
    margin-top: 11px;
}

/* navigation bar */
#navbar{
  position: sticky;
  display: flex;
  align-items: center;
  top: 0px;
  background-color: #110202;
}

#navbar .sub-menu{
  display: flex;
  position: absolute;
  right: 119px;
  top: 2px;
  
  
}
#navbar ul li {
  list-style: none;
  font-size: 1.3rem;
  text-align: center;
  font-family: 'Baloo Bhai 2', cursive;
  
}
#navbar ul li a{
  display: block;
  color: white;
  padding: 18px 14px 17px 17px;
  text-decoration: none;
  background-color: black;
}
#navbar  ul ul  {
  display: none;
}
#navbar ul li  :hover {
  
  color: rgb(143, 138, 138);
  
}
#navbar .sub-menu:hover #dropdown  {
    display: inline-block;
 }


</style>
<body>
    <form method = 'POST'>
        {% csrf_token %}
        <div class="container">
            <h1>REGISTER </h1>
            <P>Please fill in this form to create an account</P>

            <label for="email"><b>Name</b></label>
            <input type="text" placeholder="Enter Name" name="name" id="Name" required autoFocus>

            <label for="email"><b>Email</b></label>
            <input type="email" placeholder="Enter Email" name="email" id="email" required>

            <label for="psw"><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="password" id="password" required>

            <label for="psw-repeat"><b>Contact Info</b></label>
            <input type="text" placeholder="Enter Number" name="contact" id="password-repeat" required>


            <button type="submit" class="registerbtn">Register</button>
        </div>
    </form>
</body>

</html>
{% endblock content %}

ufeed/templates/ufeed/contact_info.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'ufeed/contact_info.css' %}">
     
  
</head>
<body>
            <section class="form-section">
              <div class="container">
                <h1>Contact Us</h1>
                <div class="row">
                    <div class="col-md-6">
                      <form method="POST">
                        {% csrf_token %}
                          <div class="from-row">
                            <form class="row g-3 needs-validation" novalidate>
                                <div class="col-md-4">
                                  <label for="validationCustom01" class="form-label"> Name</label>
                                  <input type="text" autoFocus class="form-control" id="validationCustom02" name="name" required>
                                  </div>
                                
                                
                                <div class="col-md-6">
                                  <label for="validationCustom03" class="form-label">Email Address</label>
                                  <input type="email" class="form-control" id="validationCustom03" name="email" required>
                                  <div class="invalid-feedback">
                                    Please provide a valid email Address.
                                  </div>
                                </div>
                                <div class="col-md-6">
                                    <label for="validationCustom03" class="form-label">subject</label>
                                    <input type="text" class="form-control" id="validationCustom03" name="subject" required>
                    
                                  </div>
                                <div class="col-md-6">
                                    <label for="validationCustom03" class="form-label"> Message</label>
                                    <div>
                                    <textarea  id="" cols="50" rows="4" name="message" required> 
                                    </textarea>
                                </div>
                                  </div>
                                
                                <div class="col-12">
                                  <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                                    <label class="form-check-label" for="invalidCheck">
                                      Confirm the Form
                                    </label>
                                    <div class="invalid-feedback">
                                      You must agree before submitting.
                                    </div>
                                  </div>
                                </div>
                                <br>
                                <div class="col-12">
                                  <button class="btn btn-primary" type="submit" >Send Message</button>
                                    
                                </div>
                              </form>
                          </div>
                        
                      </form>
                    </div>
                    <div class="col-md-6">
                    <br>
                        <h5>Contact Number</h5>
                        <p> <i class="fa fa-phone"></i>+(91) 1234567890 <br><br>
                        </p>
                        <h5>Email Address</h5>
                        <p>
                          <i class="fas fa-envelope"></i>tejas.gambhir21@vit.edu<br><br>
                        </p>
                        <h5>Working hours</h5>
                        <p>
                          Monday-Saturday : 12am - 12pm(IST)
                        </p><br>
                        <h5>Address</h5>
                        <p>
                          666, Upper Indiranagar, Bibwewadi, Pune, Maharashtra 411037 
                        </p>
                        
                    </div>

                </div>
            </div>
         </section>
    
</body>
</html>
{% endblock content %}

ufeed/templates/ufeed/donate.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>donate-food</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script>
        function validateForm() {
            alert("ok");
            let name = document.forms["myForm"]["name"].value;
            let contact = document.forms["myForm"]["contact"].value;
            let address = document.forms["myForm"]["address"].value;
            let amount = document.forms["myForm"]["amount"].value;
            if (name == "") {
                alert("Name must be filled out");
                return false;
            }
            if (contact == "") {
                alert("Contact must be filled out");
                return false;
            }
            if (address == "") {
                alert("Address must be filled out");
                return false;
            }
            if (amount == "") {
                alert("Amount must be filled out");
                return false;
            }
        }
    </script>
</head>
<style>
    body {
        background-color: aliceblue;
    }

    .container {
        width: 44vw;
        /* height: 500px; */

        margin: 40px auto;
        background-color: white;
        padding: 20px;
    }

    input[type=text],
    input[type=tel],
    input[type=textarea],
    input[type=number] {
        display: inline-block;
        padding: 10px;
        width: 100%;
        margin: 7px 0px 22px 0px;

    }

    .registerbtn {
        background-color: #04AA6D;
        color: white;
        padding: 14px 20px;
        /* margin: 8px 0; */
        border: none;
        cursor: pointer;
        width: 100%;
    }

    .registerbtn:hover {
        opacity: 0.8;
    }

    p {
        margin: 16px 0px;
    }

    * {
        box-sizing: border-box;
    }

    .title {
        text-align: center;
    }
</style>

<body>
    <form method="POST" name="myForm" onsubmit="validateForm">
        {% csrf_token %}
        <div class="container">
            <div class="title">
                <h1>Donate Food</h1>
                <p>Donate for the children</p>
            </div>

            <label for="email"><b>Name</b></label>
            <input type="text" placeholder="Enter Name" name="name" id="Name" autoFocus>

            <label for="Contact"><b>Contact</b></label>
            <input type="tel" placeholder="Enter Number" name="contact" id="contact" required>

            <label for="Address"><b>Address</b></label>
            <input type="text" placeholder="Enter Address" name="address" id="Address" required>

            <label for="Address"><b>Amount</b></label>
            <input type="number" placeholder="People It Can Feed" name="amount" id="Amount" required>

            <button type="submit" class="registerbtn">Donate</button>
        </div>
    </form>
</body>


</html>
{% endblock content %}

ufeed/templates/ufeed/donate_confirm_delete.html
<html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
    <script src="https://smtpjs.com/v3/smtp.js"></script>  
	<script type="text/javascript">
		function sendEmail() {
			Email.send({
				Host: "smtp.gmail.com",
				Username : "triptozolo4@gmail.com",
				Password : "shazam926",
				To : document.getElementById("email").value,
				From : "triptozolo4@gmail.com",
				Subject : "This is confirmation of the request ",
				Body : "Name: {{donate.name}}  <br/>  Contact: {{donate.contact}}  <br/>  Address: {{donate.address}} <br/>  these are the info related to the respective Hotels/Restaurants.",
			});
		}
	</script>
    <style>
        .confirm {
            color: white;
            background-color: orangered;
        }
    </style>

</head>

<body>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="container-fluid" style="display: flex; justify-content: center; margin-top: 20%;">
            <div class="card" style="width: 25rem;">
                
                <label for="email">Confirm Email</label>
                <input type="text" name="email" id="email" value={{user.username}}>
                <input type="submit" value="Accept" class="confirm" onclick="sendEmail()" />
            </div>
        </div>
    </form>
</body>

</html>

ufeed/templates/ufeed/home_page.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>unknown giving</title>
</head>
<link rel="stylesheet" href="{% static 'ufeed/home_page.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&family=Baloo+Bhai+2:wght@600&display=swap" rel="stylesheet">
<body>
    <div class="slide-container">
        <div class="slide">
            <img src="{% static 'ufeed/ann-tribe-children-myanmar-joxe-inazio-kuesta-garmendia.jpg' %}" alt="">
        </div>
        <div class="slide">
            <img src="{% static 'ufeed/kid-6268594__340.jpg' %}" alt="">
        </div>
        <div class="slide">
            <img src="{% static 'ufeed/loi-tribe-girl-myanmar-joxe-inazio-kuesta-garmendia.jpg' %}" alt="">
        </div>
        <div class="slide">
            <img src="{% static 'ufeed/girl-2529907__480.jpg' %}" alt="">
        </div>
    </div>                                                                         -->
    <span class="Arrow prev" onclick="controller(-1)">&#10094;</span>
    <span class="Arrow next" onclick="controller(1)">&#10095;</span>
    <div class="aboutus">
        <h1>About Us</h1>
        <p>Help us eradicate hunger in India

            194 million people in India today do not have enough food to eat, the largest in any one country in the world. According to the Global Hunger Index 2021, India falls under the 'serious' hunger category with a rank of 101 among 116 countries.
            
            These statistics however, do not take into account the effects of COVID-19. The resultant migration, unemployment and loss of earning members of households has pushed millions of Indians into extreme poverty and hunger.</p>
        <h2> Our Vision</h2>
        <P>We believe providing meals to dependents in undeserved communities to reduce financial burden on NGO's and other organizations in short term, empowering them to become free from hunger in long term.</P>
        <h2> Our Mission</h2>
        <P>Our works are designed to provid essential food support to undeserved areas in the form of food.</P>
        <h2> Our focus Area</h2>
        <P>Our focused area is hunger, through our website we can help environment in two ways by reducing food wastage and degradation and providing this food to the undeserved people. Wo don't have a bite of food to eat.</P>
    </div>
   <script>
       let index = 0 ;
       function controller(x){
             index = index + x
             slideshow(index);
       }
       slideshow(index);
       function slideshow(num){
           let slides =document.getElementsByClassName("slide");
           if (num==slides.length) {
             num =0;
             index =0;  
           }
           if (num<0) {
             index = slides.length - 1;
             num = slides.length - 1;
           }
           for(let y of slides){
                y.style.display = "none";
           }
           slides[num].style.display = "block";
       }
   </script>
</body>
</html>
{% endblock content %}

ufeed/templates/ufeed/sign_in.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign-in</title>
    <link rel="stylesheet" href="{% static 'ufeed/sign_in.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&family=Baloo+Bhai+2:wght@600&display=swap" rel="stylesheet">
</head>
<body>
    <form  method="POST">
        {% csrf_token %}
        <div class="mid-container">
            <div class="imgcontainer">
                <img src="{% static 'ufeed/avatar2.png' %}" alt="Avatar" class="avatar">
              </div>
            
              <div class="container">
                <label for="email"><b>Email</b></label>
                <input type="email" placeholder="Enter Email" name="email" required autoFocus>
            
                <label for="password"><b>Password</b></label>
                <input type="password" placeholder="Enter Password" name="password" required>
            
                <button type="submit">Login</button>
              
              </div>
        </div>
      
        
      </form>
</body>
</html>
{% endblock content %}